/**
 * src/store/seed.ts のデータから wrangler d1 execute --file 用の seed.sql を標準出力に書く。
 *   npm run seed:sql
 */
import { SEED_LINKS, SEED_OBJECTS } from "../src/store/seed.ts";

const q = (s: string): string => `'${s.replace(/'/g, "''")}'`;

const lines = [
  "-- generated by scripts/seed-sql.ts — 編集せず src/store/seed.ts を直す",
  "DELETE FROM links;",
  "DELETE FROM objects;",
  "DELETE FROM audit_log;",
  "DELETE FROM sqlite_sequence WHERE name = 'audit_log';",
  ...SEED_OBJECTS.map(
    (o) => `INSERT INTO objects (type, id, props) VALUES (${q(o.type)}, ${q(o.id)}, ${q(JSON.stringify(o.props))});`,
  ),
  ...SEED_LINKS.map((l) => `INSERT INTO links (type, from_id, to_id) VALUES (${q(l.type)}, ${q(l.from)}, ${q(l.to)});`),
];
process.stdout.write(`${lines.join("\n")}\n`);
